#pragma once
#include <string>

using namespace std;

//BACKGROUND FUNCTIONS
void readFile(int* array, string filename, int &size);
//PRE: RECIEVES NAME OF INPUT FILE, ARRAY, AND ARRAY SIZE
//POST: ARRAY IS NOW LOADED WITH ALL INTEGERS FROM INPUT FILE

//ASSIGNMENT FUNCTIONS
int mySearch(int* array, int value, int size);
//PRE: RECIEVES ARRAY, AN INTEGER, AND CURRENT ARRAY SIZE
//POST: RETURNS THE INDEX OF THE INTEGER IF FOUND OR A -1 IF NOT
//NOTE: IF DUPLICATES IN ARRAY, IT WILL RETURN THE FIRST ONE IT FINDS

void integerModifier(int* array, int &original_integer, int &new_integer);
//PRE: RECIEVES ARRAY AND TWO INITIALIZED INTEGERS
//POST: THE INTEGER AT THE SELECTED INDEX HAS BEEN MODIFIED
//POST: THE TWO INTEGERS ARE THE BEFORE AND AFTER OF THE MODIFIED INDEX

void addInteger(int* array, int &size, int input);
//PRE: RECIEVES ARRAY, ARRAY SIZE, AND INTEGER(USER PROVIDED)
//POST: ARRAY SIZE IS NOW ONE BIGGER AND INTEGER IS AT THE END OF THE ARRAY

void wipeInteger(int* array, int index);
//PRE: RECIEVES ARRAY AND INDEX
//POST: ARRAY[INDEX] NOW HOLDS THE VALUE 0
